# ===========================
# Database Configuration
# ===========================
DB_HOST=localhost
DB_PORT=5432
DB_NAME=ai_medical_hospital
DB_USER=postgres
DB_PASSWORD=Mahesh@1234

# ===========================
# JWT Configuration
# ===========================
SECRET_KEY=your_super_secret_key
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# ===========================
# Application
# ===========================
APP_NAME=AI Medical Hospital
DEBUG=True